### ISSUE TITLE
Progress bar jumps around a lot

### ISSUE THREAD

**Issue by melody-rs** [samelgamedev/osmodloader#5]
Ever since you sped up the modloader the progress bar just freezes on "finalizing files" and jumps right to the end
It *is* faster but in practice it feels slower because the bar feezes

the human mind is weird ok

**Comment by callistoAshley** [comment]
this has got something to do with windows forms and how it hates multithreading but i thought of a fix earlier and i'll implement it on the weekend

**Comment by melody-rs** [comment]
you should write the fix down so you don't forget
